
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        EVENT_ADD_NEW: "EVENT_ADD_NEW",
        ATTENDANCE_ADD_NEW: "ATTENDANCE_ADD_NEW",
        LEAVE_ADD_NEW: "LEAVE_ADD_NEW",
        MANAGE_REGISTRATION: "MANAGE_REGISTRATION",
        LEAVE_REQUEST_CONFIRMATION: "LEAVE_REQUEST_CONFIRMATION",
        EXPENSE_ADD_NEW: "EXPENSE_ADD_NEW",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
    },
});
